### ISSUE TITLE
Feature Request: create an API for the models

### ISSUE THREAD

**Issue by alew3** [da-z/mlx-ui#4]
Models run so much better on MLX than otherwise on the Mac. This could become the LMStudio alternative for Apple Silicon owners if it had an API interface to the models (following the OpenAI pattern).
Just a thought :-)

**Comment by da-z** [comment]
Hi. mlx-lm already exposes a limited OpenAI API.

See https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/SERVER.md

**Comment by da-z** [comment]
My plan is to actually make LLaMazing (my other project) use OpenAI API and support both MLX, Ollama, etc. I may contribute some code to mlx_lm to fill in some API gaps.

**Comment by alew3** [comment]
thats great! thanks for the tip!
