### ISSUE TITLE
What's the Chrome Theme for the screenshot?

### ISSUE THREAD

**Issue by wangyizhou1-tal** [da-z/mlx-ui#5]
Wonderful Work!
I really like your chrome theme but I searched for days and couldn't find any.
I'd wonder if you could share any Key words?

**Comment by da-z** [comment]
Thanks. Glad you find the project useful. You can find the theme definition in https://github.com/da-z/mlx-ui/blob/main/.streamlit/config.toml

![img-9tnbyG4O](https://github.com/da-z/mlx-ui/assets/3681019/b750e0b7-ed93-4276-a926-22953eac9fa2)

**Comment by wangyizhou1-tal** [comment]
It seems I didn't make myself clear. The streamlit theam is good enough. I want to know the theme of your browser, outside the project. I mean the green-yellow-blue fade one. It looks really cool. 
![image](https://github.com/da-z/mlx-ui/assets/131731885/c1619066-1ad8-449b-8cb6-93da6ceb5d6c)

**Comment by da-z** [comment]
Sorry, my bad :) That is actually Firefox, and the theme is called Dream of Waves. Hope this helps :)

**Comment by wangyizhou1-tal** [comment]
Got it , a lot of thanks!
