### ISSUE TITLE
[bug] Stop button isn't working

### ISSUE THREAD

**Issue by rodion-m** [da-z/mlx-ui#9]
After the launch I pressed Stop button:
![image](https://github.com/da-z/mlx-ui/assets/36400912/82bdfcb0-c18f-4953-a3b9-cbde8a629d80)

But it didn't have an effect:
![image](https://github.com/da-z/mlx-ui/assets/36400912/b76d1f78-68f9-4c7d-a063-9a55df976583)
![image](https://github.com/da-z/mlx-ui/assets/36400912/f7bfabb8-595b-4543-8de4-53ac45aa34fc)

**Comment by da-z** [comment]
Download itself is handled by mlx-lm. There is no way for me to stop it at this moment, sorry. You have to force-stop the app itself.

**Comment by rodion-m** [comment]
Ok, then what is the purpose of the Stop button?
